import json, pathlib

HEADER = {
    "cell_type": "markdown",
    "id": "header",
    "metadata": {},
    "source": [
        "# 13 — BERT Embeddings como features adicionales\n\n",
        "**Materia:** Laboratorio de Implementacion II · Universidad Austral · Abril 2026\n\n",
        "**Autores:** Roxana Alberti · Sandra Sschicchi · Fernando Paganini · Baltazar Villanueva · Paula Calviello · Rosana Martinez\n\n",
        "---\n\n",
        "## Que hace este notebook?\n\n",
        "Usamos un modelo **BERT multilingue preentrenado** para convertir la descripcion de cada mascota en un vector numerico (embedding) y lo agregamos como features adicionales al ensemble.\n\n",
        "### ¿Que es BERT?\n\n",
        "BERT (Bidirectional Encoder Representations from Transformers) es un modelo de lenguaje preentrenado sobre miles de millones de palabras. Puede leer una descripcion de texto y producir un vector de numeros que **captura el significado semantico** del texto.\n\n",
        "Ejemplo:\n",
        "- 'Cute puppy, very friendly' → [0.23, -0.11, 0.87, ...] (384 numeros)\n",
        "- 'Old dog, needs special care' → [-0.15, 0.43, -0.22, ...] (384 numeros diferentes)\n\n",
        "Nuestros modelos de arboles (LGB/XGB/CB) no pueden leer texto directamente, pero **si pueden usar esos 384 numeros** como features adicionales.\n\n",
        "### Modelo elegido\n\n",
        "Usamos `paraphrase-multilingual-MiniLM-L12-v2` (sentence-transformers):\n",
        "- Multilingue: funciona bien en ingles y malayo (el idioma del dataset)\n",
        "- Compacto: 384 dimensiones, rapido de inferir\n",
        "- Preentrenado para similitud semantica de oraciones\n\n",
        "### Estrategia\n\n",
        "| Paso | Descripcion |\n",
        "|---|---|\n",
        "| 1 | Generar embeddings BERT para cada descripcion (384 dims) |\n",
        "| 2 | Reducir con PCA a 32 componentes (fit solo en train, transform en test) |\n",
        "| 3 | Concatenar con FE v4 (48 feat) → **80 features** en total |\n",
        "| 4 | Entrenar ensemble LGB+XGB+CB con 5-fold CV + OOF |\n",
        "| 5 | Aplicar Optimized Rounder |\n",
        "| 6 | Comparar con record 0.4242 (nb11) |\n"
    ]
}

SEC_A = {"cell_type": "markdown", "id": "sec_a_md", "metadata": {}, "source": ["## Seccion A: Instalacion e imports"]}

INSTALL = {
    "cell_type": "code",
    "execution_count": None,
    "id": "install",
    "metadata": {},
    "outputs": [],
    "source": [
        "# Instalar sentence-transformers (no viene en Colab por defecto)\n",
        "import subprocess\n",
        "subprocess.run(['pip', 'install', 'sentence-transformers', '-q'], check=True)\n",
        "print('sentence-transformers instalado OK')\n"
    ]
}

SETUP = {
    "cell_type": "code",
    "execution_count": None,
    "id": "setup",
    "metadata": {},
    "outputs": [],
    "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import lightgbm as lgb\n",
        "import xgboost as xgb\n",
        "from catboost import CatBoostClassifier\n",
        "from scipy.optimize import minimize\n",
        "from functools import partial\n",
        "from sklearn.metrics import cohen_kappa_score\n",
        "from sklearn.model_selection import train_test_split, StratifiedKFold\n",
        "from sklearn.decomposition import PCA\n",
        "from sentence_transformers import SentenceTransformer\n",
        "from pathlib import Path\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "BASE_DIR = Path.cwd()\n",
        "while not (BASE_DIR / 'input').exists() and BASE_DIR != BASE_DIR.parent:\n",
        "    BASE_DIR = BASE_DIR.parent\n",
        "print(f'BASE_DIR: {BASE_DIR}')\n",
        "\n",
        "SEED = 42\n",
        "train_raw = pd.read_csv(BASE_DIR / 'input/train/train.csv')\n",
        "sent_df   = pd.read_csv(BASE_DIR / 'input/train_sentiment_features.csv')\n",
        "meta_df   = pd.read_csv(BASE_DIR / 'input/train_metadata_features.csv')\n",
        "train_raw['desc_length'] = train_raw['Description'].fillna('').apply(len)\n",
        "\n",
        "df = (train_raw\n",
        "      .merge(sent_df[['PetID','sentiment_score','sentiment_magnitude','n_sentences']], on='PetID', how='left')\n",
        "      .merge(meta_df[['PetID','avg_label_score','n_labels','crop_confidence']], on='PetID', how='left')\n",
        "      .fillna(0))\n",
        "\n",
        "train, test = train_test_split(df, test_size=0.2, random_state=SEED, stratify=df['AdoptionSpeed'])\n",
        "print(f'Train: {len(train)} | Test: {len(test)}')\n"
    ]
}

SEC_B = {"cell_type": "markdown", "id": "sec_b_md", "metadata": {}, "source": [
    "## Seccion B: BERT Embeddings\n\n",
    "Generamos embeddings para la columna `Description` de cada mascota.\n\n",
    "- Si la descripcion esta vacia, usamos el string vacio (BERT devuelve un vector de ceros semanticos).\n",
    "- Procesamos en batches de 128 para mayor eficiencia en GPU.\n\n",
    "⏳ *Esta seccion tarda ~2-5 minutos en GPU T4.*"
]}

BERT_CODE = {
    "cell_type": "code",
    "execution_count": None,
    "id": "bert_code",
    "metadata": {},
    "outputs": [],
    "source": [
        "print('Cargando modelo BERT multilingue...')\n",
        "bert_model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')\n",
        "print(f'Modelo cargado. Dimensiones de embedding: {bert_model.get_sentence_embedding_dimension()}')\n",
        "\n",
        "# Preparar descripciones (usar string vacio si es nulo/cero)\n",
        "def clean_desc(x):\n",
        "    if x == 0 or str(x).strip() == '' or str(x) == 'nan':\n",
        "        return ''\n",
        "    return str(x).strip()\n",
        "\n",
        "all_descriptions = df['Description'].apply(clean_desc).tolist()\n",
        "\n",
        "print(f'Generando embeddings para {len(all_descriptions)} mascotas...')\n",
        "all_embeddings = bert_model.encode(\n",
        "    all_descriptions,\n",
        "    batch_size=128,\n",
        "    show_progress_bar=True,\n",
        "    device='cuda' if __import__('torch').cuda.is_available() else 'cpu'\n",
        ")\n",
        "print(f'Embeddings generados: shape = {all_embeddings.shape}')\n",
        "\n",
        "# Asignar embeddings al dataframe segun indice\n",
        "embed_df = pd.DataFrame(all_embeddings, index=df.index,\n",
        "                        columns=[f'bert_{i}' for i in range(all_embeddings.shape[1])])\n",
        "df_with_bert = df.join(embed_df)\n",
        "\n",
        "# Re-split con el mismo random_state para que train/test coincidan\n",
        "train_b, test_b = train_test_split(df_with_bert, test_size=0.2, random_state=SEED,\n",
        "                                   stratify=df_with_bert['AdoptionSpeed'])\n",
        "BERT_COLS = [f'bert_{i}' for i in range(all_embeddings.shape[1])]\n",
        "print(f'Split OK — train: {len(train_b)} | test: {len(test_b)}')\n"
    ]
}

SEC_C = {"cell_type": "markdown", "id": "sec_c_md", "metadata": {}, "source": [
    "## Seccion C: PCA — reduccion de dimensionalidad\n\n",
    "Reducimos los 384 dims de BERT a **32 componentes principales**.\n\n",
    "**¿Por que PCA?**\n",
    "- 384 features de BERT + 48 de FE v4 = 432 features totales: demasiado para los arboles\n",
    "- PCA captura las 32 direcciones de mayor varianza en el espacio semantico\n",
    "- **Importante:** fit del PCA solo sobre el train set, luego transform en test (sin data leakage)\n\n",
    "Con 32 componentes retenemos tipicamente ~70-80% de la varianza total de BERT."
]}

PCA_CODE = {
    "cell_type": "code",
    "execution_count": None,
    "id": "pca_code",
    "metadata": {},
    "outputs": [],
    "source": [
        "N_COMPONENTS = 32\n",
        "\n",
        "pca = PCA(n_components=N_COMPONENTS, random_state=SEED)\n",
        "train_bert_pca = pca.fit_transform(train_b[BERT_COLS].values)  # fit solo en train\n",
        "test_bert_pca  = pca.transform(test_b[BERT_COLS].values)        # transform en test\n",
        "\n",
        "var_explained = pca.explained_variance_ratio_.sum()\n",
        "print(f'PCA {N_COMPONENTS} componentes — varianza explicada: {var_explained:.1%}')\n",
        "\n",
        "PCA_COLS = [f'bert_pca_{i}' for i in range(N_COMPONENTS)]\n",
        "train_pca_df = pd.DataFrame(train_bert_pca, columns=PCA_COLS, index=train_b.index)\n",
        "test_pca_df  = pd.DataFrame(test_bert_pca,  columns=PCA_COLS, index=test_b.index)\n",
        "\n",
        "train_aug = train_b.join(train_pca_df)\n",
        "test_aug  = test_b.join(test_pca_df)\n",
        "print(f'Features BERT PCA agregadas: {N_COMPONENTS}')\n"
    ]
}

SEC_D = {"cell_type": "markdown", "id": "sec_d_md", "metadata": {}, "source": ["## Seccion D: Feature Engineering v4 + BERT"]}

FE_CODE = {
    "cell_type": "code",
    "execution_count": None,
    "id": "fe_code",
    "metadata": {},
    "outputs": [],
    "source": [
        "def target_encode(train_df, test_df, col, target='AdoptionSpeed', smoothing=10):\n",
        "    global_mean = train_df[target].mean()\n",
        "    stats = train_df.groupby(col)[target].agg(['mean', 'count'])\n",
        "    stats['encoded'] = (stats['count'] * stats['mean'] + smoothing * global_mean) / (stats['count'] + smoothing)\n",
        "    return train_df[col].map(stats['encoded']).fillna(global_mean), test_df[col].map(stats['encoded']).fillna(global_mean)\n",
        "\n",
        "def add_features_v4(df_):\n",
        "    df_ = df_.copy()\n",
        "    df_['HasPhoto']            = (df_['PhotoAmt'] > 0).astype(int)\n",
        "    df_['HasVideo']            = (df_['VideoAmt'] > 0).astype(int)\n",
        "    df_['IsFree']              = (df_['Fee'] == 0).astype(int)\n",
        "    df_['AgeGroup']            = pd.cut(df_['Age'], bins=[-1,3,12,48,9999], labels=[0,1,2,3]).astype(int)\n",
        "    df_['HealthScore']         = ((df_['Vaccinated']==1).astype(int) + (df_['Dewormed']==1).astype(int) + (df_['Sterilized']==1).astype(int))\n",
        "    df_['IsPureBreed']         = (df_['Breed2'] == 0).astype(int)\n",
        "    df_['PhotoPerAnimal']      = df_['PhotoAmt'] / df_['Quantity'].replace(0,1)\n",
        "    df_['Age_x_PhotoAmt']      = df_['Age'] * df_['PhotoAmt']\n",
        "    df_['IsPureBreed_x_Age']   = df_['IsPureBreed'] * df_['AgeGroup']\n",
        "    df_['HealthScore_x_Photo'] = df_['HealthScore'] * df_['HasPhoto']\n",
        "    df_['IsYoungAndFree']      = ((df_['AgeGroup'] <= 1) & (df_['IsFree'] == 1)).astype(int)\n",
        "    df_['IsHealthyAndPhoto']   = ((df_['HealthScore'] == 3) & (df_['HasPhoto'] == 1)).astype(int)\n",
        "    df_['FeePerAnimal']        = df_['Fee'] / df_['Quantity'].replace(0,1)\n",
        "    return df_\n",
        "\n",
        "def nlp_feats(df_):\n",
        "    desc = df_['Description'].apply(lambda x: '' if (x == 0 or str(x).strip() == '') else str(x))\n",
        "    df_['word_count']      = desc.apply(lambda x: len(x.split()))\n",
        "    df_['unique_words']    = desc.apply(lambda x: len(set(x.lower().split())))\n",
        "    df_['avg_word_len']    = desc.apply(lambda x: round(sum(len(w) for w in x.split()) / max(len(x.split()),1), 2))\n",
        "    df_['uppercase_ratio'] = desc.apply(lambda x: round(sum(c.isupper() for c in x) / max(len(x),1), 4))\n",
        "    df_['has_exclamation'] = desc.apply(lambda x: int('!' in x))\n",
        "    return df_\n",
        "\n",
        "tr = train_aug.copy(); te = test_aug.copy()\n",
        "tr['Breed1_enc'], te['Breed1_enc'] = target_encode(tr, te, 'Breed1')\n",
        "tr['State_enc'],  te['State_enc']  = target_encode(tr, te, 'State')\n",
        "\n",
        "rescuer_count = tr.groupby('RescuerID').size().rename('rescuer_n_pets')\n",
        "tr['rescuer_n_pets'] = tr['RescuerID'].map(rescuer_count).fillna(1)\n",
        "te['rescuer_n_pets'] = te['RescuerID'].map(rescuer_count).fillna(1)\n",
        "\n",
        "age_med_map = tr.groupby(['Breed1','Type'])['Age'].median().to_dict()\n",
        "global_age  = tr['Age'].median()\n",
        "for df_ in [tr, te]:\n",
        "    df_['age_median_bt'] = [age_med_map.get((b,t), global_age) for b,t in zip(df_['Breed1'], df_['Type'])]\n",
        "    df_['age_rel_breed'] = df_['Age'] / (df_['age_median_bt'] + 1)\n",
        "\n",
        "tr = nlp_feats(tr); te = nlp_feats(te)\n",
        "tr = add_features_v4(tr); te = add_features_v4(te)\n",
        "\n",
        "TABULAR_FEATURES = [\n",
        "    'Type','Age','Breed1','Breed2','Gender','Color1','Color2','Color3',\n",
        "    'MaturitySize','FurLength','Vaccinated','Dewormed','Sterilized',\n",
        "    'Health','Quantity','Fee','State','VideoAmt','PhotoAmt',\n",
        "    'HasPhoto','HasVideo','IsFree','AgeGroup','HealthScore','IsPureBreed','PhotoPerAnimal',\n",
        "    'Age_x_PhotoAmt','IsPureBreed_x_Age','HealthScore_x_Photo','IsYoungAndFree','IsHealthyAndPhoto','FeePerAnimal',\n",
        "    'sentiment_score','sentiment_magnitude','n_sentences','avg_label_score','n_labels','crop_confidence','desc_length',\n",
        "    'Breed1_enc','State_enc',\n",
        "    'rescuer_n_pets','age_rel_breed','word_count','unique_words','avg_word_len','uppercase_ratio','has_exclamation'\n",
        "]\n",
        "ALL_FEATURES = TABULAR_FEATURES + PCA_COLS  # 48 + 32 = 80 features\n",
        "\n",
        "X_train = tr[ALL_FEATURES]; X_test = te[ALL_FEATURES]\n",
        "y_train = tr['AdoptionSpeed']; y_test = te['AdoptionSpeed']\n",
        "print(f'Features totales: {len(ALL_FEATURES)} ({len(TABULAR_FEATURES)} tabulares + {len(PCA_COLS)} BERT PCA)')\n"
    ]
}

SEC_E = {"cell_type": "markdown", "id": "sec_e_md", "metadata": {}, "source": [
    "## Seccion E: Entrenamiento ensemble + Optimized Rounder\n\n",
    "Mismos parametros que nb11. Ahora cada modelo ve **80 features** en lugar de 48.\n\n",
    "⏳ *Esta seccion tarda ~20-25 minutos.*"
]}

TRAIN_CODE = {
    "cell_type": "code",
    "execution_count": None,
    "id": "train_code",
    "metadata": {},
    "outputs": [],
    "source": [
        "skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)\n",
        "\n",
        "lgb_oof  = np.zeros((len(X_train), 5)); xgb_oof  = np.zeros((len(X_train), 5)); cb_oof  = np.zeros((len(X_train), 5))\n",
        "lgb_test = np.zeros((len(X_test),  5)); xgb_test = np.zeros((len(X_test),  5)); cb_test = np.zeros((len(X_test),  5))\n",
        "\n",
        "lgb_params = {\n",
        "    'objective': 'multiclass', 'num_class': 5, 'verbosity': -1,\n",
        "    'num_leaves': 51, 'lambda_l1': 0.10, 'lambda_l2': 7.58,\n",
        "    'feature_fraction': 0.59, 'bagging_fraction': 0.98,\n",
        "    'bagging_freq': 1, 'min_child_samples': 118, 'learning_rate': 0.093\n",
        "}\n",
        "xgb_params = {\n",
        "    'objective': 'multi:softprob', 'num_class': 5, 'verbosity': 0,\n",
        "    'max_depth': 6, 'learning_rate': 0.05, 'n_estimators': 500,\n",
        "    'subsample': 0.8, 'colsample_bytree': 0.8, 'reg_alpha': 0.1,\n",
        "    'reg_lambda': 1.0, 'min_child_weight': 5, 'random_state': SEED,\n",
        "    'tree_method': 'hist', 'device': 'cuda'\n",
        "}\n",
        "cb_params = {\n",
        "    'loss_function': 'MultiClass', 'eval_metric': 'Accuracy',\n",
        "    'random_seed': SEED, 'verbose': False, 'early_stopping_rounds': 20,\n",
        "    'iterations': 800, 'depth': 6, 'learning_rate': 0.19071087606036805,\n",
        "    'l2_leaf_reg': 19.723764128240514, 'bagging_temperature': 0.22376847772452582,\n",
        "    'border_count': 196, 'min_data_in_leaf': 13, 'task_type': 'GPU'\n",
        "}\n",
        "\n",
        "for fold, (tr_idx, val_idx) in enumerate(skf.split(X_train, y_train)):\n",
        "    print(f'  Fold {fold+1}/5...', end=' ')\n",
        "    X_tr, X_val = X_train.iloc[tr_idx], X_train.iloc[val_idx]\n",
        "    y_tr, y_val = y_train.iloc[tr_idx], y_train.iloc[val_idx]\n",
        "\n",
        "    m_lgb = lgb.train(lgb_params, lgb.Dataset(X_tr, label=y_tr), num_boost_round=500,\n",
        "                      valid_sets=[lgb.Dataset(X_val, label=y_val)],\n",
        "                      callbacks=[lgb.early_stopping(20, verbose=False)])\n",
        "    lgb_oof[val_idx] = m_lgb.predict(X_val)\n",
        "    lgb_test += m_lgb.predict(X_test)\n",
        "\n",
        "    m_xgb = xgb.XGBClassifier(**xgb_params)\n",
        "    m_xgb.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], verbose=False)\n",
        "    xgb_oof[val_idx] = m_xgb.predict_proba(X_val)\n",
        "    xgb_test += m_xgb.predict_proba(X_test)\n",
        "\n",
        "    m_cb = CatBoostClassifier(**cb_params)\n",
        "    m_cb.fit(X_tr, y_tr, eval_set=(X_val, y_val), use_best_model=True)\n",
        "    cb_oof[val_idx] = m_cb.predict_proba(X_val)\n",
        "    cb_test += m_cb.predict_proba(X_test)\n",
        "    print('OK')\n",
        "\n",
        "def norm(arr): return arr / arr.sum(axis=1, keepdims=True)\n",
        "lgb_oof_n  = norm(lgb_oof);  xgb_oof_n  = norm(xgb_oof);  cb_oof_n  = norm(cb_oof)\n",
        "lgb_test_n = norm(lgb_test); xgb_test_n = norm(xgb_test); cb_test_n = norm(cb_test)\n",
        "\n",
        "W_LGB, W_XGB, W_CB = 0.30, 0.45, 0.25\n",
        "oof_blend  = W_LGB * lgb_oof_n  + W_XGB * xgb_oof_n  + W_CB * cb_oof_n\n",
        "test_blend = W_LGB * lgb_test_n + W_XGB * xgb_test_n + W_CB * cb_test_n\n",
        "\n",
        "CLASS_WEIGHTS = np.array([0, 1, 2, 3, 4])\n",
        "oof_score  = oof_blend  @ CLASS_WEIGHTS\n",
        "test_score = test_blend @ CLASS_WEIGHTS\n",
        "\n",
        "def apply_thresholds(score, thresholds):\n",
        "    return np.clip(np.digitize(score, bins=np.sort(thresholds)), 0, 4)\n",
        "\n",
        "def kappa_loss(thresholds, score, y):\n",
        "    return -cohen_kappa_score(y, apply_thresholds(score, thresholds), weights='quadratic')\n",
        "\n",
        "print('Optimizando umbrales...')\n",
        "result = minimize(partial(kappa_loss, score=oof_score, y=y_train.values),\n",
        "                  [0.5, 1.5, 2.5, 3.5], method='nelder-mead',\n",
        "                  options={'xatol': 1e-6, 'fatol': 1e-6, 'maxiter': 20000})\n",
        "optimal_thresholds = np.sort(result.x)\n",
        "\n",
        "test_preds_opt = apply_thresholds(test_score, optimal_thresholds)\n",
        "kappa_bert = cohen_kappa_score(y_test, test_preds_opt, weights='quadratic')\n",
        "print(f'Umbrales optimos: {[f\"{t:.4f}\" for t in optimal_thresholds]}')\n",
        "print(f'\\nEnsemble + BERT PCA32 + Opt. Rounder — Test kappa: {kappa_bert:.4f}')\n"
    ]
}

SEC_F = {"cell_type": "markdown", "id": "sec_f_md", "metadata": {}, "source": ["## Seccion F: Comparativa final"]}

FINAL_COMP = {
    "cell_type": "code",
    "execution_count": None,
    "id": "final_comp",
    "metadata": {},
    "outputs": [],
    "source": [
        "KAPPA_NB11 = 0.4242  # record anterior (Opt. Rounder sin BERT)\n",
        "delta = kappa_bert - KAPPA_NB11\n",
        "\n",
        "print('='*75)\n",
        "print('  COMPARATIVA FINAL — Evolucion completa del proyecto')\n",
        "print('='*75)\n",
        "print(f'  Baseline (19 feat)                            Test: 0.3133')\n",
        "print(f'  FE v3 + Optuna (39 feat)                      Test: 0.3595  (+0.0462)')\n",
        "print(f'  FE v4 + 5-fold CV (48 feat)                   Test: 0.3867  (+0.0734)')\n",
        "print(f'  Ensemble LGB+XGB+CB blend (nb10)              Test: 0.3951  (+0.0818)')\n",
        "print(f'  Ensemble + Optimized Rounder (nb11) — RECORD  Test: {KAPPA_NB11:.4f}  ({KAPPA_NB11-0.3133:+.4f})')\n",
        "print(f'  Stacking LR + Opt. Rounder (nb12)             Test: 0.4215  (+0.1082)')\n",
        "print(f'  BERT PCA32 + Ensemble + Opt. Rounder (nb13)   Test: {kappa_bert:.4f}  ({kappa_bert-0.3133:+.4f})')\n",
        "print('='*75)\n",
        "\n",
        "if delta > 0:\n",
        "    print(f'  -> BERT MEJORA el record en {delta:+.4f}  NUEVO RECORD: {kappa_bert:.4f}')\n",
        "else:\n",
        "    print(f'  -> BERT no supera el record ({delta:+.4f})')\n",
        "    print(f'     Las features tabulares ya capturan bien la informacion del texto.')\n",
        "    print(f'     El registro de Google Vision/NLP ya incluye sentiment y metadata.')\n",
        "print('='*75)\n",
        "\n",
        "# Feature importance — top BERT PCA components\n",
        "import lightgbm as lgb_fi\n",
        "m_fi = lgb_fi.train(lgb_params, lgb_fi.Dataset(X_train, label=y_train), num_boost_round=300)\n",
        "fi = pd.Series(m_fi.feature_importance('gain'), index=ALL_FEATURES).sort_values(ascending=False)\n",
        "bert_fi = fi[fi.index.str.startswith('bert_pca')]\n",
        "tab_fi  = fi[~fi.index.str.startswith('bert_pca')]\n",
        "print(f'\\nTop 5 features tabulares:')\n",
        "print(tab_fi.head(5).to_string())\n",
        "print(f'\\nTop 5 BERT PCA components:')\n",
        "print(bert_fi.head(5).to_string())\n",
        "bert_total_pct = bert_fi.sum() / fi.sum() * 100\n",
        "print(f'\\nContribucion total BERT en feature importance: {bert_total_pct:.1f}%')\n"
    ]
}

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "cells": [
        HEADER, SEC_A, INSTALL, SETUP,
        SEC_B, BERT_CODE,
        SEC_C, PCA_CODE,
        SEC_D, FE_CODE,
        SEC_E, TRAIN_CODE,
        SEC_F, FINAL_COMP
    ]
}

out = pathlib.Path(__file__).parent / '13_BERT_Embeddings_Roxy.ipynb'
with open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print(f'Creado: {out}')
