import json, pathlib

HEADER = {
    "cell_type": "markdown",
    "id": "header",
    "metadata": {},
    "source": [
        "# 11 — Optimized Rounder: umbrales optimos para Kappa\n\n",
        "**Materia:** Laboratorio de Implementacion II · Universidad Austral · Abril 2026\n\n",
        "**Autores:** Roxana Alberti · Sandra Sschicchi · Fernando Paganini · Baltazar Villanueva · Paula Calviello · Rosana Martinez\n\n",
        "---\n\n",
        "## Que hace este notebook?\n\n",
        "Aplicamos un **Optimized Rounder** al ensemble LGB+XGB+CatBoost del nb10.\n\n",
        "### El problema del redondeo estandar\n\n",
        "Nuestros modelos producen probabilidades para 5 clases (AdoptionSpeed 0-4). ",
        "Normalmente convertimos eso a una clase con `argmax` (clase con mayor probabilidad). ",
        "Pero tambien podemos calcular un **score continuo** como promedio ponderado:\n\n",
        "```\n",
        "score = 0*p(0) + 1*p(1) + 2*p(2) + 3*p(3) + 4*p(4)\n",
        "```\n\n",
        "Luego necesitamos **umbrales (thresholds)** para convertir ese score en clase:\n",
        "- score < t0 → clase 0\n",
        "- t0 ≤ score < t1 → clase 1\n",
        "- ...\n\n",
        "El redondeo estandar usa t0=0.5, t1=1.5, t2=2.5, t3=3.5. ",
        "Pero como las clases NO estan balanceadas en PetFinder, estos umbrales no son optimos.\n\n",
        "### Solucion: Optimized Rounder\n",
        "Usamos `scipy.optimize.minimize` (Nelder-Mead) para encontrar los 4 umbrales que ",
        "**maximizan el Cohen Kappa cuadratico** sobre las predicciones OOF (out-of-fold).\n\n",
        "| Paso | Descripcion |\n",
        "|---|---|\n",
        "| 1 | Entrenar LGB+XGB+CB con 5-fold CV, guardar OOF predictions |\n",
        "| 2 | Blend OOF: LGB(30%)+XGB(45%)+CB(25%) |\n",
        "| 3 | Convertir a score continuo [0,4] |\n",
        "| 4 | Optimizar 4 umbrales sobre OOF score (sin tocar test set) |\n",
        "| 5 | Aplicar umbrales optimos al test set |\n"
    ]
}

SEC_A = {"cell_type": "markdown", "id": "sec_a_md", "metadata": {}, "source": ["## Seccion A: Imports y datos"]}

SETUP = {
    "cell_type": "code",
    "execution_count": None,
    "id": "setup",
    "metadata": {},
    "outputs": [],
    "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import lightgbm as lgb\n",
        "import xgboost as xgb\n",
        "from catboost import CatBoostClassifier\n",
        "from scipy.optimize import minimize\n",
        "from functools import partial\n",
        "from sklearn.metrics import cohen_kappa_score\n",
        "from sklearn.model_selection import train_test_split, StratifiedKFold\n",
        "from pathlib import Path\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "BASE_DIR = Path.cwd()\n",
        "while not (BASE_DIR / 'input').exists() and BASE_DIR != BASE_DIR.parent:\n",
        "    BASE_DIR = BASE_DIR.parent\n",
        "print(f'BASE_DIR: {BASE_DIR}')\n",
        "\n",
        "SEED = 42\n",
        "train_raw = pd.read_csv(BASE_DIR / 'input/train/train.csv')\n",
        "sent_df   = pd.read_csv(BASE_DIR / 'input/train_sentiment_features.csv')\n",
        "meta_df   = pd.read_csv(BASE_DIR / 'input/train_metadata_features.csv')\n",
        "train_raw['desc_length'] = train_raw['Description'].fillna('').apply(len)\n",
        "\n",
        "df = (train_raw\n",
        "      .merge(sent_df[['PetID','sentiment_score','sentiment_magnitude','n_sentences']], on='PetID', how='left')\n",
        "      .merge(meta_df[['PetID','avg_label_score','n_labels','crop_confidence']], on='PetID', how='left')\n",
        "      .fillna(0))\n",
        "\n",
        "train, test = train_test_split(df, test_size=0.2, random_state=SEED, stratify=df['AdoptionSpeed'])\n",
        "print(f'Train: {len(train)} | Test: {len(test)}')\n"
    ]
}

SEC_B = {"cell_type": "markdown", "id": "sec_b_md", "metadata": {}, "source": ["## Seccion B: Feature Engineering v4"]}

FE_CODE = {
    "cell_type": "code",
    "execution_count": None,
    "id": "fe_code",
    "metadata": {},
    "outputs": [],
    "source": [
        "def target_encode(train_df, test_df, col, target='AdoptionSpeed', smoothing=10):\n",
        "    global_mean = train_df[target].mean()\n",
        "    stats = train_df.groupby(col)[target].agg(['mean', 'count'])\n",
        "    stats['encoded'] = (stats['count'] * stats['mean'] + smoothing * global_mean) / (stats['count'] + smoothing)\n",
        "    return train_df[col].map(stats['encoded']).fillna(global_mean), test_df[col].map(stats['encoded']).fillna(global_mean)\n",
        "\n",
        "def add_features_v4(df_):\n",
        "    df_ = df_.copy()\n",
        "    df_['HasPhoto']            = (df_['PhotoAmt'] > 0).astype(int)\n",
        "    df_['HasVideo']            = (df_['VideoAmt'] > 0).astype(int)\n",
        "    df_['IsFree']              = (df_['Fee'] == 0).astype(int)\n",
        "    df_['AgeGroup']            = pd.cut(df_['Age'], bins=[-1,3,12,48,9999], labels=[0,1,2,3]).astype(int)\n",
        "    df_['HealthScore']         = ((df_['Vaccinated']==1).astype(int) + (df_['Dewormed']==1).astype(int) + (df_['Sterilized']==1).astype(int))\n",
        "    df_['IsPureBreed']         = (df_['Breed2'] == 0).astype(int)\n",
        "    df_['PhotoPerAnimal']      = df_['PhotoAmt'] / df_['Quantity'].replace(0,1)\n",
        "    df_['Age_x_PhotoAmt']      = df_['Age'] * df_['PhotoAmt']\n",
        "    df_['IsPureBreed_x_Age']   = df_['IsPureBreed'] * df_['AgeGroup']\n",
        "    df_['HealthScore_x_Photo'] = df_['HealthScore'] * df_['HasPhoto']\n",
        "    df_['IsYoungAndFree']      = ((df_['AgeGroup'] <= 1) & (df_['IsFree'] == 1)).astype(int)\n",
        "    df_['IsHealthyAndPhoto']   = ((df_['HealthScore'] == 3) & (df_['HasPhoto'] == 1)).astype(int)\n",
        "    df_['FeePerAnimal']        = df_['Fee'] / df_['Quantity'].replace(0,1)\n",
        "    return df_\n",
        "\n",
        "def nlp_feats(df_):\n",
        "    desc = df_['Description'].apply(lambda x: '' if (x == 0 or str(x).strip() == '') else str(x))\n",
        "    df_['word_count']      = desc.apply(lambda x: len(x.split()))\n",
        "    df_['unique_words']    = desc.apply(lambda x: len(set(x.lower().split())))\n",
        "    df_['avg_word_len']    = desc.apply(lambda x: round(sum(len(w) for w in x.split()) / max(len(x.split()),1), 2))\n",
        "    df_['uppercase_ratio'] = desc.apply(lambda x: round(sum(c.isupper() for c in x) / max(len(x),1), 4))\n",
        "    df_['has_exclamation'] = desc.apply(lambda x: int('!' in x))\n",
        "    return df_\n",
        "\n",
        "train = train.copy(); test = test.copy()\n",
        "train['Breed1_enc'], test['Breed1_enc'] = target_encode(train, test, 'Breed1')\n",
        "train['State_enc'],  test['State_enc']  = target_encode(train, test, 'State')\n",
        "\n",
        "rescuer_count = train.groupby('RescuerID').size().rename('rescuer_n_pets')\n",
        "train['rescuer_n_pets'] = train['RescuerID'].map(rescuer_count).fillna(1)\n",
        "test['rescuer_n_pets']  = test['RescuerID'].map(rescuer_count).fillna(1)\n",
        "\n",
        "age_med_map = train.groupby(['Breed1','Type'])['Age'].median().to_dict()\n",
        "global_age  = train['Age'].median()\n",
        "for df_ in [train, test]:\n",
        "    df_['age_median_bt'] = [age_med_map.get((b,t), global_age) for b,t in zip(df_['Breed1'], df_['Type'])]\n",
        "    df_['age_rel_breed'] = df_['Age'] / (df_['age_median_bt'] + 1)\n",
        "\n",
        "train = nlp_feats(train); test = nlp_feats(test)\n",
        "train_fe = add_features_v4(train); test_fe = add_features_v4(test)\n",
        "\n",
        "ALL_FEATURES = [\n",
        "    'Type','Age','Breed1','Breed2','Gender','Color1','Color2','Color3',\n",
        "    'MaturitySize','FurLength','Vaccinated','Dewormed','Sterilized',\n",
        "    'Health','Quantity','Fee','State','VideoAmt','PhotoAmt',\n",
        "    'HasPhoto','HasVideo','IsFree','AgeGroup','HealthScore','IsPureBreed','PhotoPerAnimal',\n",
        "    'Age_x_PhotoAmt','IsPureBreed_x_Age','HealthScore_x_Photo','IsYoungAndFree','IsHealthyAndPhoto','FeePerAnimal',\n",
        "    'sentiment_score','sentiment_magnitude','n_sentences','avg_label_score','n_labels','crop_confidence','desc_length',\n",
        "    'Breed1_enc','State_enc',\n",
        "    'rescuer_n_pets','age_rel_breed','word_count','unique_words','avg_word_len','uppercase_ratio','has_exclamation'\n",
        "]\n",
        "\n",
        "X_train = train_fe[ALL_FEATURES]; X_test = test_fe[ALL_FEATURES]\n",
        "y_train = train_fe['AdoptionSpeed']; y_test = test_fe['AdoptionSpeed']\n",
        "print(f'Features: {len(ALL_FEATURES)}')\n"
    ]
}

SEC_C = {"cell_type": "markdown", "id": "sec_c_md", "metadata": {}, "source": [
    "## Seccion C: Entrenamiento ensemble con OOF predictions\n\n",
    "Entrenamos los tres modelos con 5-fold CV y guardamos las predicciones **out-of-fold (OOF)**.\n\n",
    "Las predicciones OOF son las predicciones del modelo sobre los datos que NO vio durante el entrenamiento.\n",
    "Esto es clave: usamos estas OOF predictions para calibrar el rounder **sin tocar el test set**.\n\n",
    "### Parametros (mismos que nb10 — mejor ensemble)\n",
    "- LGB: `num_leaves=51, lambda_l2=7.58, lr=0.093`\n",
    "- XGB: `max_depth=6, lr=0.05, n_estimators=500`\n",
    "- CB: `depth=6, lr=0.191, l2=19.7` (Optuna nb10)\n",
    "- Pesos blend: **LGB 30% + XGB 45% + CB 25%**\n\n",
    "⏳ *Esta seccion tarda ~15-20 minutos.*"
]}

TRAIN_OOF = {
    "cell_type": "code",
    "execution_count": None,
    "id": "train_oof",
    "metadata": {},
    "outputs": [],
    "source": [
        "skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)\n",
        "\n",
        "# Arrays para OOF y test\n",
        "lgb_oof  = np.zeros((len(X_train), 5))\n",
        "xgb_oof  = np.zeros((len(X_train), 5))\n",
        "cb_oof   = np.zeros((len(X_train), 5))\n",
        "lgb_test = np.zeros((len(X_test),  5))\n",
        "xgb_test = np.zeros((len(X_test),  5))\n",
        "cb_test  = np.zeros((len(X_test),  5))\n",
        "\n",
        "lgb_params = {\n",
        "    'objective': 'multiclass', 'num_class': 5, 'verbosity': -1,\n",
        "    'num_leaves': 51, 'lambda_l1': 0.10, 'lambda_l2': 7.58,\n",
        "    'feature_fraction': 0.59, 'bagging_fraction': 0.98,\n",
        "    'bagging_freq': 1, 'min_child_samples': 118, 'learning_rate': 0.093\n",
        "}\n",
        "xgb_params = {\n",
        "    'objective': 'multi:softprob', 'num_class': 5, 'verbosity': 0,\n",
        "    'max_depth': 6, 'learning_rate': 0.05, 'n_estimators': 500,\n",
        "    'subsample': 0.8, 'colsample_bytree': 0.8, 'reg_alpha': 0.1,\n",
        "    'reg_lambda': 1.0, 'min_child_weight': 5, 'random_state': SEED,\n",
        "    'tree_method': 'hist', 'device': 'cpu'\n",
        "}\n",
        "cb_params = {\n",
        "    'loss_function': 'MultiClass', 'eval_metric': 'Accuracy',\n",
        "    'random_seed': SEED, 'verbose': False, 'early_stopping_rounds': 20,\n",
        "    'iterations': 800, 'depth': 6, 'learning_rate': 0.19071087606036805,\n",
        "    'l2_leaf_reg': 19.723764128240514, 'bagging_temperature': 0.22376847772452582,\n",
        "    'border_count': 196, 'min_data_in_leaf': 13\n",
        "}\n",
        "\n",
        "for fold, (tr_idx, val_idx) in enumerate(skf.split(X_train, y_train)):\n",
        "    print(f'  Fold {fold+1}/5...', end=' ')\n",
        "    X_tr, X_val = X_train.iloc[tr_idx], X_train.iloc[val_idx]\n",
        "    y_tr, y_val = y_train.iloc[tr_idx], y_train.iloc[val_idx]\n",
        "\n",
        "    # LightGBM\n",
        "    m_lgb = lgb.train(lgb_params, lgb.Dataset(X_tr, label=y_tr), num_boost_round=500,\n",
        "                      valid_sets=[lgb.Dataset(X_val, label=y_val)],\n",
        "                      callbacks=[lgb.early_stopping(20, verbose=False)])\n",
        "    lgb_oof[val_idx] = m_lgb.predict(X_val)\n",
        "    lgb_test += m_lgb.predict(X_test)\n",
        "\n",
        "    # XGBoost\n",
        "    m_xgb = xgb.XGBClassifier(**xgb_params)\n",
        "    m_xgb.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], verbose=False)\n",
        "    xgb_oof[val_idx] = m_xgb.predict_proba(X_val)\n",
        "    xgb_test += m_xgb.predict_proba(X_test)\n",
        "\n",
        "    # CatBoost\n",
        "    m_cb = CatBoostClassifier(**cb_params)\n",
        "    m_cb.fit(X_tr, y_tr, eval_set=(X_val, y_val), use_best_model=True)\n",
        "    cb_oof[val_idx] = m_cb.predict_proba(X_val)\n",
        "    cb_test += m_cb.predict_proba(X_test)\n",
        "    print('OK')\n",
        "\n",
        "# Normalizar probabilidades\n",
        "def norm(arr): return arr / arr.sum(axis=1, keepdims=True)\n",
        "lgb_oof_n  = norm(lgb_oof);  xgb_oof_n  = norm(xgb_oof);  cb_oof_n  = norm(cb_oof)\n",
        "lgb_test_n = norm(lgb_test); xgb_test_n = norm(xgb_test); cb_test_n = norm(cb_test)\n",
        "\n",
        "# Blend con pesos optimos de nb10\n",
        "W_LGB, W_XGB, W_CB = 0.30, 0.45, 0.25\n",
        "oof_blend  = W_LGB * lgb_oof_n  + W_XGB * xgb_oof_n  + W_CB * cb_oof_n\n",
        "test_blend = W_LGB * lgb_test_n + W_XGB * xgb_test_n + W_CB * cb_test_n\n",
        "\n",
        "# Kappa sin rounder optimizado (argmax estandar)\n",
        "kappa_oof_argmax  = cohen_kappa_score(y_train, oof_blend.argmax(axis=1),  weights='quadratic')\n",
        "kappa_test_argmax = cohen_kappa_score(y_test,  test_blend.argmax(axis=1), weights='quadratic')\n",
        "print(f'\\nSin Optimized Rounder — OOF: {kappa_oof_argmax:.4f} | Test: {kappa_test_argmax:.4f}')\n"
    ]
}

SEC_D = {"cell_type": "markdown", "id": "sec_d_md", "metadata": {}, "source": [
    "## Seccion D: Optimized Rounder\n\n",
    "Convertimos las probabilidades del blend a un **score continuo** y buscamos los 4 umbrales optimos.\n\n",
    "### Score continuo\n",
    "```\n",
    "score = 0*p(clase=0) + 1*p(clase=1) + 2*p(clase=2) + 3*p(clase=3) + 4*p(clase=4)\n",
    "```\n\n",
    "### Optimizacion\n",
    "Usamos `scipy.optimize.minimize` con metodo Nelder-Mead para encontrar los 4 umbrales [t0, t1, t2, t3] ",
    "que minimizan `-kappa(y_oof, digitize(score_oof, thresholds))`.\n\n",
    "**Importante:** el rounder se ajusta sobre las predicciones OOF (nunca sobre test). ",
    "Esto garantiza que no hay data leakage."
]}

ROUNDER_CODE = {
    "cell_type": "code",
    "execution_count": None,
    "id": "rounder_code",
    "metadata": {},
    "outputs": [],
    "source": [
        "# Score continuo: promedio ponderado de clases\n",
        "CLASS_WEIGHTS = np.array([0, 1, 2, 3, 4])\n",
        "oof_score  = oof_blend  @ CLASS_WEIGHTS\n",
        "test_score = test_blend @ CLASS_WEIGHTS\n",
        "\n",
        "def apply_thresholds(score, thresholds):\n",
        "    \"\"\"Convierte score continuo a clase usando umbrales ordenados.\"\"\"\n",
        "    t = np.sort(thresholds)\n",
        "    preds = np.digitize(score, bins=t)\n",
        "    return np.clip(preds, 0, 4)\n",
        "\n",
        "def kappa_loss(thresholds, score, y):\n",
        "    \"\"\"Funcion a minimizar: negativo del kappa cuadratico.\"\"\"\n",
        "    preds = apply_thresholds(score, thresholds)\n",
        "    return -cohen_kappa_score(y, preds, weights='quadratic')\n",
        "\n",
        "# Punto de inicio: umbrales estandar\n",
        "init_thresholds = [0.5, 1.5, 2.5, 3.5]\n",
        "\n",
        "# Optimizar sobre OOF predictions\n",
        "print('Optimizando umbrales sobre predicciones OOF...')\n",
        "loss_fn = partial(kappa_loss, score=oof_score, y=y_train.values)\n",
        "result = minimize(loss_fn, init_thresholds, method='nelder-mead',\n",
        "                  options={'xatol': 1e-6, 'fatol': 1e-6, 'maxiter': 20000})\n",
        "optimal_thresholds = np.sort(result.x)\n",
        "\n",
        "print(f'Umbrales estandar:  [0.5, 1.5, 2.5, 3.5]')\n",
        "print(f'Umbrales optimos:   {[f\"{t:.4f}\" for t in optimal_thresholds]}')\n",
        "\n",
        "# Kappa OOF con umbrales optimos (referencia interna)\n",
        "oof_preds_opt  = apply_thresholds(oof_score,  optimal_thresholds)\n",
        "kappa_oof_opt  = cohen_kappa_score(y_train, oof_preds_opt, weights='quadratic')\n",
        "\n",
        "# Kappa TEST con umbrales optimos\n",
        "test_preds_opt  = apply_thresholds(test_score, optimal_thresholds)\n",
        "kappa_test_opt  = cohen_kappa_score(y_test, test_preds_opt, weights='quadratic')\n",
        "\n",
        "print(f'\\nKappa OOF  — estandar: {kappa_oof_argmax:.4f}  optimizado: {kappa_oof_opt:.4f}  delta: {kappa_oof_opt - kappa_oof_argmax:+.4f}')\n",
        "print(f'Kappa Test — estandar: {kappa_test_argmax:.4f}  optimizado: {kappa_test_opt:.4f}  delta: {kappa_test_opt - kappa_test_argmax:+.4f}')\n"
    ]
}

SEC_E = {"cell_type": "markdown", "id": "sec_e_md", "metadata": {}, "source": ["## Seccion E: Comparativa final"]}

FINAL_COMP = {
    "cell_type": "code",
    "execution_count": None,
    "id": "final_comp",
    "metadata": {},
    "outputs": [],
    "source": [
        "print('='*75)\n",
        "print('  COMPARATIVA FINAL — Evolucion completa del proyecto')\n",
        "print('='*75)\n",
        "print(f'  Baseline (19 feat)                  Test: 0.3133')\n",
        "print(f'  FE v1 (26 feat)                     Test: 0.3231  (+0.0099)')\n",
        "print(f'  FE v2 + Optuna simple (32 feat)      Test: 0.3371  (+0.0238)')\n",
        "print(f'  FE v3 + Optuna simple (39 feat)      Test: 0.3595  (+0.0462)')\n",
        "print(f'  FE v4 + 5-fold CV (48 feat)          Test: 0.3867  (+0.0734)')\n",
        "print(f'  Ensemble LGB+XGB+CB (nb10)           Test: 0.3951  (+0.0818)')\n",
        "print(f'  Ensemble + Optimized Rounder (nb11)  Test: {kappa_test_opt:.4f}  ({kappa_test_opt - 0.3133:+.4f} vs baseline)')\n",
        "print('='*75)\n",
        "mejora = kappa_test_opt - 0.3951\n",
        "if mejora > 0:\n",
        "    print(f'  -> Optimized Rounder mejora el ensemble en {mejora:+.4f}')\n",
        "else:\n",
        "    print(f'  -> Optimized Rounder no mejora el ensemble en este split ({mejora:+.4f})')\n",
        "    print(f'     Nota: el rounder puede ser mas util en un CV completo o con el dataset real de Kaggle')\n",
        "print('='*75)\n",
        "print(f'\\nDistribucion de predicciones con Optimized Rounder:')\n",
        "from collections import Counter\n",
        "dist = Counter(test_preds_opt)\n",
        "dist_std = Counter(test_blend.argmax(axis=1))\n",
        "for cls in range(5):\n",
        "    print(f'  Clase {cls}: estandar={dist_std.get(cls,0):4d}  optimizado={dist.get(cls,0):4d}')\n"
    ]
}

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "cells": [HEADER, SEC_A, SETUP, SEC_B, FE_CODE, SEC_C, TRAIN_OOF, SEC_D, ROUNDER_CODE, SEC_E, FINAL_COMP]
}

out = pathlib.Path(__file__).parent / '11_OptimizedRounder_Roxy.ipynb'
with open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print(f'Creado: {out}')
